# Pandas Cleaning

In [10]:
import pandas as pd

df = pd.read_csv("../Data/data_jobs.csv")
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'], errors='coerce')

## Date and Time

### Datetime

#### Notes

* `pd.to_datetime()`: Convert argument to datetime.

#### Example

In our DataFrame the `job_posted_date` is actually a string not a datetime format. First let's convert it to datetime format. 

We'll also use `info()` to check if the data type changed from a string to a `datetime` format.

In [7]:
# Convert 'job_posted_date' to datetime without specifying the exact format
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'], errors='coerce')
# Takes in Series - data structure - 1D labeled array

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

### Date

#### Notes

* `dt`: accessor that provides a way to access specialized methods and properties we use to work with datatime data within a pandas series. 
* `date`: extract the date component from the datetime object in the series. 
* Use together `dt.date` on our series.

#### Example

Now let's turn it from a datetime to a date using `dt.date`.

In [9]:
df['job_posted_date'] = df['job_posted_date'].dt.date

df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

## Sorting Values

* `sort_values()` sorts a DataFrame or a specific column in ascending or descending order based on one or more columns. 
* Typically this is used to sort by a specific column/s.
* Parameters: 
    * `by` - column name or list of column names to sort by
    * `ascending` - boolean or list of booleans, default `True`, to sort by descending you would use `False`
    * `inplace` - whether to modify the DataFrame in place or return a new one

<br>
Let's sort our DataFrame by the `job_posted_date` in descending order (from most recent date to least).

In [10]:
df.sort_values(by='job_posted_date', ascending=False, inplace=True)
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
287457,Senior Data Engineer,Senior Data Engineer,"Randburg, South Africa",via CareerJunction,Full-time,False,South Africa,2023-12-31,False,False,South Africa,NaN,NaN,NaN,DCV Sabenza IT and Recruitment,"['sql', 'python', 'databricks', 'azure', 'hado...","{'analyst_tools': ['ssrs', 'power bi', 'tablea..."
233330,Data Analyst,Data Analyst,"Philadelphia, PA",via ZipRecruiter,Part-time and Per diem,False,"New York, United States",2023-12-31,False,False,United States,NaN,NaN,NaN,Drexel University,NaN,NaN
528676,Data Engineer,Data Engineer (Híbrida en Monterrey o Ciudad M...,"Monterrey, Nuevo Leon, Mexico",via LinkedIn,Full-time,False,Mexico,2023-12-31,True,False,Mexico,NaN,NaN,NaN,Listopro,"['java', 'scala', 'sql', 'nosql', 'mongodb', '...","{'cloud': ['aws', 'azure', 'oracle'], 'databas..."
165223,Data Engineer,HYBRID -DATA ENGINEER- (AWS) Certified Data An...,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-12-31,False,False,United States,NaN,NaN,NaN,Dice,"['python', 'sql', 'nosql', 'aws', 'flow']","{'cloud': ['aws'], 'other': ['flow'], 'program..."
499568,Data Scientist,Analytics Engineer,"Gelang Patah, Johor, Malaysia",via LinkedIn,NaN,False,Malaysia,2023-12-31,False,False,Malaysia,NaN,NaN,NaN,Insulet Corporation,"['sql', 'mongodb', 'mongodb', 'python', 'azure...","{'cloud': ['azure', 'bigquery', 'databricks'],..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
776626,Software Engineer,Application Support Analyst with SQL,"Warsaw, Poland",via Trabajo.org,Full-time,False,Poland,2023-01-01,True,False,Poland,NaN,NaN,NaN,Bravura Solutions Polska Sp. z o.o.,"['t-sql', 'linux', 'windows']","{'os': ['linux', 'windows'], 'programming': ['..."
295569,Senior Data Scientist,Senior Data Scientist/Computer Vision Scientist,"Paris, France",via BeBee,Full-time,False,France,2023-01-01,False,False,France,NaN,NaN,NaN,SkillCorner,"['python', 'numpy', 'scikit-learn', 'opencv', ...","{'libraries': ['numpy', 'scikit-learn', 'openc..."
365141,Data Analyst,Data Analyst,"Foster City, CA",via LinkedIn,Full-time,False,"California, United States",2023-01-01,True,False,United States,NaN,NaN,NaN,Netpace Inc,"['sql', 'python', 'oracle', 'excel', 'word', '...","{'analyst_tools': ['excel', 'word', 'sap'], 'c..."
82608,Business Analyst,Senior Solution Analyst- GAMMA Retail Catalyst,"Warsaw, Poland",via Boston Consulting Group,Full-time,False,Poland,2023-01-01,False,False,Poland,NaN,NaN,NaN,"BCG GAMMA, Boston Consulting Group","['sql', 'python', 'go', 'alteryx', 'excel', 'p...","{'analyst_tools': ['alteryx', 'excel', 'powerp..."
347766,Data Engineer,"Manager, Data Engineering, SMAI","Bengaluru, Karnataka, India",via Careers At Micron Technology,Full-time,False,India,2023-01-01,False,False,India,NaN,NaN,NaN,Micron Technology,"['python', 'snowflake', 'gcp', 'hadoop']","{'cloud': ['snowflake', 'gcp'], 'libraries': [..."

## Adding a Column

- If you want to create a column you'll need to use the `df['column_name']` syntax.

<br>
Here we are creating a new column called 'Is Data Analyst' and saying if the column `job_title_short` is equal to 'Data Analyst' then then return 1 if not, return 0. It does this by using `astype(int)`.

In [17]:
df['Is Data Analyst'] = (df.job_title_short == 'Data Analyst').astype(int)

Let's view this new column we created.

In [18]:
df['Is Data Analyst']

702239    1
714269    0
250599    1
313161    0
327439    0
         ..
777985    0
41270     0
776813    0
365786    0
334082    0
Name: Is Data Analyst, Length: 22003, dtype: int64

Did this work? Let's look at cases when this column is greater than 0, which means it is equal to 1 (aka it's true). We can use our row filtering we learned in the last section.

In [19]:
df[df['Is Data Analyst'] > 0]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,company_name,job_skills,job_type_skills,Is Data Analyst
702239,Data Analyst,Technical Data Analyst,"Manila, Metro Manila, Philippines",via Ai-Jobs.net,Full-time,False,Philippines,2023-12-31,False,False,Philippines,year,89204.0,SupportNinja,"['windows', 'excel', 'jira']","{'analyst_tools': ['excel'], 'async': ['jira']...",1
250599,Data Analyst,Supply Chain Analytics Manager,Anywhere,via Get.It,Full-time,True,"California, United States",2023-12-31,False,True,United States,year,83000.0,Get It Recruit - Transportation,NaN,NaN,1
120858,Data Analyst,Machine Learning Data Analyst,Anywhere,via Get.It,Full-time,True,"California, United States",2023-12-31,False,True,United States,year,144000.0,Get It Recruit - Information Technology,"['sql', 'python', 'matplotlib', 'tableau', 'po...","{'analyst_tools': ['tableau', 'power bi'], 'li...",1
421728,Data Analyst,Data Analyst - Operations,"Los Angeles, CA",via Indeed,Full-time,False,"California, United States",2023-12-31,False,True,United States,year,72750.0,Wilshire Law Firm Plc,"['sql', 'power bi', 'unity']","{'analyst_tools': ['power bi'], 'other': ['uni...",1
572665,Data Analyst,Data Analyst,"King of Prussia, PA",via BeBee,Full-time,False,"New York, United States",2023-12-30,True,False,United States,year,100000.0,Liberty Personnel Services,"['sql', 'python', 'powershell', 'snowflake']","{'cloud': ['snowflake'], 'programming': ['sql'...",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47131,Data Analyst,HR Data Analyst,"Washington, DC",via Indeed,Full-time,False,"New York, United States",2023-01-01,True,True,United States,year,77500.0,CyberCoders,['sharepoint'],{'analyst_tools': ['sharepoint']},1
710182,Data Analyst,Junior Data Analyst,"Gland, Switzerland",via Ai-Jobs.net,Full-time,False,Switzerland,2023-01-01,True,False,Switzerland,year,51000.0,Swissquote,NaN,NaN,1
728461,Data Analyst,Data Analyst,California,via LinkedIn,Contractor,False,"California, United States",2023-01-01,False,False,United States,year,92500.0,Robert Half,"['sql', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ...",1
467812,Data Analyst,SHS DATA ANALYST,"New York, NY",via LinkedIn,Full-time,False,"New York, United States",2023-01-01,False,True,United States,year,81167.0,NYC Department of Social Services,NaN,NaN,1
366073,Data Analyst,Data Analytics Professional,"Atlanta, GA",via CareerBuilder,Full-time,False,Georgia,2023-01-01,False,False,United States,year,55000.0,Cogent Infotech.,"['sql', 'python', 'numpy', 'pandas', 'seaborn'...","{'analyst_tools': ['excel', 'alteryx', 'tablea...",1

## Dropping Data

* Use `drop()` if you want to drop (delete) either a column or row in your database. 
* The syntax is:
    * Drop column: `df.drop('column_name', axis = 1)`
    * Drop row: `df.drop(index_name, axis = 0)`
* If you wanted to drop multiple rows you would have the syntax: 
    * Drop multiple columns: `df.drop(['column_name1', 'column_name2'], axis=1)`
    * Drop multiple rows: `df.drop([index_name1, index_name2], axis=0)`


<br>
Let's drop the column `'salary_hour_avg'`, this will have an axis of 1 (since we're dropping a column).

In [11]:
df.drop('salary_hour_avg', axis = 1, inplace=True)

Inspecting the columns available now:

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 785741 entries, 287457 to 347766
Data columns (total 16 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  company_name           785723 non-null  object
 14  job_skills             668704 non-null  object
 15  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(1), object(12)
memory usage: 86.2+ MB

## Remove NA

* To remove rows that contain empty cells use `dropna()`. 
* By default `dropna()` will return a *new* DataFrame, and won't change the original. 

<br>
Let's cleanup our `salary_year_avg` column by removing the `NaN` values in this column.

In [14]:
df.salary_year_avg.head()

287457   NaN
233330   NaN
528676   NaN
165223   NaN
499568   NaN
Name: salary_year_avg, dtype: float64

In [ ]:
df.dropna(subset=['salary_year_avg'], inplace=True)

In [33]:
df.salary_year_avg.head()

702239     89204.0
714269    191000.0
250599     83000.0
313161    114062.5
327439    140000.0
Name: salary_year_avg, dtype: float64

## Filling Missings

How can we fill the missing values with something else?

- `df.fillna()`: Fill missing values

Let's fill in instances where there's no salary info (aka these columns have NaN values `salary_rate`, `salary_year_avg`, `salary_hour_avg`) with 0.

In [26]:
df.loc[:10, 'salary_year_avg':'salary_hour_avg']

    salary_year_avg  salary_hour_avg
0               NaN              NaN
1               NaN              NaN
2               NaN              NaN
3               NaN              NaN
4               NaN              NaN
5               NaN              NaN
6               NaN              NaN
7               NaN              NaN
8               NaN              NaN
9               NaN              NaN
10              NaN              NaN

In [11]:
df_filled = df.fillna(0)
df_filled.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785741 non-null  object
 2   job_location           785741 non-null  object
 3   job_via                785741 non-null  object
 4   job_schedule_type      785741 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785741 non-null  object
 11  salary_rate            785741 non-null  object
 12  salary_year_avg        785741 non-null  float64
 13  salary_hour_avg        785741 non-null  float64
 14  company_name           785741 non-null  object
 15  job_skills             785741 non-null  object
 16  job_type_skills        785741 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

In [15]:
df_filled.loc[:10, 'salary_year_avg':'salary_hour_avg']

    salary_year_avg  salary_hour_avg
0               0.0              0.0
1               0.0              0.0
2               0.0              0.0
3               0.0              0.0
4               0.0              0.0
5               0.0              0.0
6               0.0              0.0
7               0.0              0.0
8               0.0              0.0
9               0.0              0.0
10              0.0              0.0

Or fill in with median values

- `copy()`: Copy a DataFrame.

In [18]:
cols = ["salary_year_avg", "salary_hour_avg"]

df_filled_1 = df.copy()
df_filled_1[cols].median(numeric_only=True)
df_filled_1[cols] = df_filled_1[cols].fillna(df_filled_1[cols].median(numeric_only=True))
df_filled_1.loc[:10, 'salary_year_avg':'salary_hour_avg']

    salary_year_avg  salary_hour_avg
0          115000.0            45.98
1          115000.0            45.98
2          115000.0            45.98
3          115000.0            45.98
4          115000.0            45.98
5          115000.0            45.98
6          115000.0            45.98
7          115000.0            45.98
8          115000.0            45.98
9          115000.0            45.98
10         115000.0            45.98

## Removing Duplicates

* `drop_duplicates()`: Remove duplicate rows.
* Analysts will often need to clean up data and one of the most common issues we run into is duplicate values.

In [38]:
df_unique = df_filled.drop_duplicates()
df_unique.info()

<class 'pandas.core.frame.DataFrame'>
Index: 785640 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785640 non-null  object
 1   job_title              785640 non-null  object
 2   job_location           785640 non-null  object
 3   job_via                785640 non-null  object
 4   job_schedule_type      785640 non-null  object
 5   job_work_from_home     785640 non-null  bool
 6   search_location        785640 non-null  object
 7   job_posted_date        785640 non-null  datetime64[ns]
 8   job_no_degree_mention  785640 non-null  bool
 9   job_health_insurance   785640 non-null  bool
 10  job_country            785640 non-null  object
 11  salary_rate            785640 non-null  object
 12  salary_year_avg        785640 non-null  float64
 13  salary_hour_avg        785640 non-null  float64
 14  company_name           785640 non-null  object
 15  job_skills             785640 non-null  object
 16  job_type_skills        785640 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 92.2+ MB

In [40]:
df_unique = df_filled.drop_duplicates(subset=['job_title', 'company_name'])
df_unique.info()

<class 'pandas.core.frame.DataFrame'>
Index: 508042 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        508042 non-null  object
 1   job_title              508042 non-null  object
 2   job_location           508042 non-null  object
 3   job_via                508042 non-null  object
 4   job_schedule_type      508042 non-null  object
 5   job_work_from_home     508042 non-null  bool
 6   search_location        508042 non-null  object
 7   job_posted_date        508042 non-null  datetime64[ns]
 8   job_no_degree_mention  508042 non-null  bool
 9   job_health_insurance   508042 non-null  bool
 10  job_country            508042 non-null  object
 11  salary_rate            508042 non-null  object
 12  salary_year_avg        508042 non-null  float64
 13  salary_hour_avg        508042 non-null  float64
 14  company_name           508042 non-null  object
 15  job_skills             508042 non-null  object
 16  job_type_skills        508042 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 59.6+ MB