# Pandas Analyzing

In [1]:
import pandas as pd

df = pd.read_csv("../_Data/data_jobs.csv")
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'], errors='coerce')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

## Descriptive Statistics

### Describe()

* It gets the following (for columns with **numeric** data):
  * count
  * mean
  * std
  * min
  * max
* Great for getting a quick overview of the basic stats for the table.
* It automatically skips NaN values.

In [27]:
df.describe()

                     job_posted_date  salary_year_avg  salary_hour_avg
count                         785741     22003.000000     10662.000000
mean   2023-06-25 16:02:11.860248576    123286.274072        47.016598
min              2023-01-01 00:00:04     15000.000000         8.000000
25%              2023-03-20 10:05:48     90000.000000        27.500000
50%              2023-06-29 06:11:38    115000.000000        45.980000
75%              2023-09-27 01:01:16    150000.000000        61.159996
max              2023-12-31 23:59:58    960000.000000       391.000000
std                              NaN     48312.449482        21.890738

In [28]:
df['salary_year_avg'].describe()

count     22003.000000
mean     123286.274072
std       48312.449482
min       15000.000000
25%       90000.000000
50%      115000.000000
75%      150000.000000
max      960000.000000
Name: salary_year_avg, dtype: float64

### Common Data Analysis Methods
* `df.count()` - Count of values
* `df.sum()` - Sum of values
* `df.cumsum()` - Cummulative sum of values
* `df.min()`/`df.max()` - Minimum/maximum values
* `df.idxmin()`/`df.idxmax()` - Indexes of minimum/Maximum value
* `df.mean()` - Mean of values
* `df.median()` - Median of values
* `df.mode()` - Mode of the values 
* `series.value_counts()` - Counts of unique values for a Series (aka a column)
    * Typically used for counting *unique occurrences* within a single column. 
    * It's not applicable to an entire DataFrame without specifying a column.
* Depending on the method, you can apply it directly to a DataFrame or a Series.

In [5]:
df.count()

job_title_short          785741
job_title                785740
job_location             784696
job_via                  785733
job_schedule_type        773074
job_work_from_home       785741
search_location          785741
job_posted_date          785741
job_no_degree_mention    785741
job_health_insurance     785741
job_country              785692
salary_rate               33067
salary_year_avg           22003
salary_hour_avg           10662
company_name             785723
job_skills               668704
job_type_skills          668704
dtype: int64

In [9]:
df['salary_year_avg'].median()

np.float64(115000.0)

In [10]:
df.iloc[df['salary_year_avg'].idxmin()]

job_title_short                                              Data Engineer
job_title                                           Data Engineer - Hadoop
job_location                                                        Brazil
job_via                                                       via LinkedIn
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                                     Brazil
job_posted_date                                        2023-12-09 10:05:30
job_no_degree_mention                                                 True
job_health_insurance                                                 False
job_country                                                         Brazil
salary_rate                                                           year
salary_year_avg                                                    15000.0
salary_hour_avg                                                        NaN
company_name                                               Net2Source Inc.
job_skills               ['java', 'python', 'oracle', 'aws', 'hadoop', ...
job_type_skills          {'cloud': ['oracle', 'aws'], 'libraries': ['ha...
Name: 665729, dtype: object

In [37]:
#df.groupby('job_title_short')['job_title_short'].count()
df['job_title_short'].value_counts()

job_title_short
Data Analyst                 196075
Data Engineer                186241
Data Scientist               172286
Business Analyst              49063
Software Engineer             44929
Senior Data Engineer          44563
Senior Data Scientist         36957
Senior Data Analyst           29216
Machine Learning Engineer     14080
Cloud Engineer                12331
Name: count, dtype: int64

## Aggregation

### Groupby()

Use `groupby` to group your DataFrame by the unique values in a specific column.
Lets you perform aggregation (e.g. mean, sum) on the grouped data.

Aggregations you can perform:
* `mean()`: Computes the mean of the groups
* `sum()`: Calculates the sum of the group values
* `median()`: Finds the median of each group
* `min()` and `max()`: Determine the minimum and maximum values within each group
* Counts:
  * `count()`: Counts the number of non-NA/null entries in each group
  * `size()`: Returns the size of each group (including NA/null values)
* `std()` and `var()`: Calculate the standard deviation and variance of groups
* `first()` and `last()`: Get the first and last row of each group
* `unique()`: Counts the number of unique non-NA/null values in each group

In [6]:
# df.groupby("columns to group")["columns to aggregate"].your_agg_method()

df.groupby('job_title_short')['salary_year_avg'].median()

job_title_short
Business Analyst              85000.0
Cloud Engineer                90000.0
Data Analyst                  90000.0
Data Engineer                125000.0
Data Scientist               127500.0
Machine Learning Engineer    106415.0
Senior Data Analyst          111175.0
Senior Data Engineer         147500.0
Senior Data Scientist        155500.0
Software Engineer             99150.0
Name: salary_year_avg, dtype: float64

In [7]:
df.groupby(['job_title_short', 'job_country'])['salary_year_avg'].median()

job_title_short    job_country
Business Analyst   Afghanistan        NaN
                   Albania            NaN
                   Algeria            NaN
                   Angola             NaN
                   Argentina      71100.0
                                   ...
Software Engineer  Venezuela          NaN
                   Vietnam        53600.0
                   Yemen              NaN
                   Zambia             NaN
                   Zimbabwe           NaN
Name: salary_year_avg, Length: 1387, dtype: float64

In [10]:
df.groupby('job_title_short')[['salary_year_avg', 'salary_hour_avg']].min()

                           salary_year_avg  salary_hour_avg
job_title_short
Business Analyst                   16500.0           10.835
Cloud Engineer                     42000.0           18.500
Data Analyst                       25000.0            8.000
Data Engineer                      15000.0            8.000
Data Scientist                     27000.0            8.000
Machine Learning Engineer          30000.0           10.000
Senior Data Analyst                30000.0           13.000
Senior Data Engineer               35000.0           12.500
Senior Data Scientist              45000.0           17.500
Software Engineer                  28000.0           11.000

* `agg()` lets you apply multiple functions at once.
* You can pass a list of functions to `agg()` to apply them all to the grouped data, or a dictionary to apply specific functions to specific columns.

In [11]:
df.groupby('job_title_short')[['salary_year_avg', 'salary_hour_avg']].agg(['min', 'max'])

                          salary_year_avg           salary_hour_avg
                                      min       max             min    max
job_title_short
Business Analyst                  16500.0  387460.0          10.835  132.5
Cloud Engineer                    42000.0  280000.0          18.500   91.0
Data Analyst                      25000.0  650000.0           8.000  391.0
Data Engineer                     15000.0  525000.0           8.000  184.5
Data Scientist                    27000.0  960000.0           8.000  237.5
Machine Learning Engineer         30000.0  325000.0          10.000   87.5
Senior Data Analyst               30000.0  425000.0          13.000  130.0
Senior Data Engineer              35000.0  425000.0          12.500  170.0
Senior Data Scientist             45000.0  890000.0          17.500  150.0
Software Engineer                 28000.0  375000.0          11.000  102.5

In [5]:
summary = df.groupby('job_title_short').agg(
    postings=('job_title_short', 'size'),
    avg_salary_year=('salary_year_avg', 'mean'),
    avg_salary_hour=('salary_hour_avg', 'mean'),
    remote_posts=('job_work_from_home', 'sum'),      # counts True
    remote_rate=('job_work_from_home', 'mean'),      # fraction True
)

summary

,postings,avg_salary_year,avg_salary_hour,remote_posts,remote_rate
job_title_short,,,,,
Business Analyst,49063,91082.612833,42.723415,2789,0.056845
Cloud Engineer,12331,111268.453846,45.560715,571,0.046306
Data Analyst,196075,93841.907854,38.106918,13326,0.067964
Data Engineer,186241,130125.604250,57.196998,21211,0.113890
Data Scientist,172286,135988.837171,49.361403,14535,0.084366
Machine Learning Engineer,14080,126774.315972,48.477935,1488,0.105682
Senior Data Analyst,29216,113911.363665,47.661218,2344,0.080230
Senior Data Engineer,44563,145840.611624,62.848496,6559,0.147185
Senior Data Scientist,36957,154206.292996,54.105631,3799,0.102795
Software Engineer,44929,113393.760054,46.452019,2930,0.065214

In [ ]:
df.groupby('job_country')['job_title_short'].count()

# ~ df.groupby('job_country').size()

job_country
Afghanistan      16
Albania         119
Algeria         111
Angola           11
Argentina      8736
               ...
Venezuela        69
Vietnam        2414
Yemen            10
Zambia          104
Zimbabwe         81
Name: job_title_short, Length: 160, dtype: int64

## Problems

In [39]:
df['job_country'].value_counts().head(5)

job_country
United States     206292
India              51088
United Kingdom     40375
France             39922
Germany            27694
Name: count, dtype: int64

In [40]:
df['job_country'].isin(['Brazil']).any()

np.True_

In [ ]:
us_jobs = df[(df['job_country'] == 'United States') & (df['salary_year_avg'].notna())]

us_jobs.groupby('job_title_short')['salary_year_avg'].agg(['median', 'min', 'max', 'count']).sort_values(by='median', ascending=False)

                             median      min       max  count
job_title_short
Senior Data Scientist      155000.0  55000.0  475000.0   1241
Machine Learning Engineer  150000.0  44408.5  315000.0    128
Senior Data Engineer       150000.0  45000.0  375000.0   1058
Data Scientist             130000.0  30000.0  960000.0   4553
Software Engineer          130000.0  48982.0  375000.0    157
Data Engineer              125000.0  23496.0  525000.0   2915
Cloud Engineer             116100.0  42000.0  221844.0     20
Senior Data Analyst        110000.0  35360.0  425000.0    913
Business Analyst            90000.0  35000.0  387460.0    431
Data Analyst                90000.0  25000.0  375000.0   4350