# Pandas Accessing Data

In [40]:
import pandas as pd

df = pd.read_csv("../_Data/data_jobs.csv")
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'], errors='coerce')

In [14]:
df.loc[:, 'salary_rate':'salary_hour_avg'].dropna(subset='salary_rate')

       salary_rate  salary_year_avg  salary_hour_avg
28            year         109500.0              NaN
43            hour              NaN             97.5
51            hour              NaN             72.5
77            year         140000.0              NaN
92            year         120000.0              NaN
...            ...              ...              ...
785624        year         139216.0              NaN
785641        year         150000.0              NaN
785648        year         221875.0              NaN
785682        year         157500.0              NaN
785692        year         157500.0              NaN

[33067 rows x 3 columns]

In [17]:
df[['job_title', 'job_location']].head()

,job_title,job_location
0,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT"
1,Data Analyst,"Guadalajara, Jalisco, Mexico"
2,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany"
3,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX"
4,Data Engineer- Sr Jobs,"Washington, DC"

In [42]:
df.iloc[:5, [1, 2]]

,job_title,job_location
0,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT"
1,Data Analyst,"Guadalajara, Jalisco, Mexico"
2,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany"
3,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX"
4,Data Engineer- Sr Jobs,"Washington, DC"

In [25]:
df.loc[5:10, 'job_title':'job_posted_date']

,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date
5,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59
6,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18
7,Data Engineer,Anywhere,via LinkedIn,Full-time,True,Romania,2023-12-07 13:40:49
8,Technology & Operations Business Analyst,"Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark,2023-06-05 13:44:34
9,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57
10,Erfahrene*r Data Engineer*in (m/w/d),"Basel, Switzerland",via LinkedIn,Full-time,False,Switzerland,2023-04-17 13:27:32

In [46]:
df_us = df[df['job_country'] == 'United States'].iloc[:15]
df_us[['job_title', 'salary_year_avg']]

                                            job_title  salary_year_avg
0   Senior Clinical Data Engineer / Principal Clin...              NaN
3   LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...              NaN
5                                   GCP Data Engineer              NaN
6                   Senior Data Engineer  - GCP Cloud              NaN
9                                   Data Scientist II              NaN
11                                      Data Engineer              NaN
13                               Senior Data Engineer              NaN
17                             Data Science Team Lead              NaN
26                                      Data Engineer              NaN
27  Principal Data Engineer (Lead), Knowledge Grap...              NaN
30     Senior Data Engineer (Work from home Eligible)              NaN
32   Sr. Data Scientist (NLP) - Full-time / Part-time              NaN
35                        Data Engineer - Royal Canin              NaN
36                                       Data Analyst              NaN
37                     Data Engineer III - Now Hiring              NaN

In [47]:
df_us = df[df['job_country'] == 'United States'].reset_index(drop=True).loc[:14, ['job_title', 'salary_year_avg']]
df_us

                                            job_title  salary_year_avg
0   Senior Clinical Data Engineer / Principal Clin...              NaN
1   LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...              NaN
2                                   GCP Data Engineer              NaN
3                   Senior Data Engineer  - GCP Cloud              NaN
4                                   Data Scientist II              NaN
5                                       Data Engineer              NaN
6                                Senior Data Engineer              NaN
7                              Data Science Team Lead              NaN
8                                       Data Engineer              NaN
9   Principal Data Engineer (Lead), Knowledge Grap...              NaN
10     Senior Data Engineer (Work from home Eligible)              NaN
11   Sr. Data Scientist (NLP) - Full-time / Part-time              NaN
12                        Data Engineer - Royal Canin              NaN
13                                       Data Analyst              NaN
14                     Data Engineer III - Now Hiring              NaN

In [50]:
start = pd.Timestamp('2023-05-01')

df[df['job_posted_date'] > start].iloc[:15][['job_title', 'job_location', 'job_posted_date']]

,job_title,job_location,job_posted_date
0,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",2023-06-16 13:44:15
2,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",2023-10-10 13:14:55
3,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",2023-07-04 13:01:41
4,Data Engineer- Sr Jobs,"Washington, DC",2023-08-07 14:29:36
5,GCP Data Engineer,Anywhere,2023-11-07 14:01:59
7,Data Engineer,Anywhere,2023-12-07 13:40:49
8,Technology & Operations Business Analyst,"Copenhagen, Denmark",2023-06-05 13:44:34
11,Data Engineer,"Colorado Springs, CO (+3 others)",2023-11-03 13:06:51
12,Stagiaire Data Analyst (H/F) - Lyon (69006),"Lyon, France",2023-12-22 13:24:41
13,Senior Data Engineer,"New York, NY",2023-11-15 13:08:52
14,Data Engineer,"Rio de Janeiro, State of Rio de Janeiro, Brazil",2023-07-13 13:17:51
15,Data Engineer,"Aberdeen, UK",2023-10-19 13:37:16
16,Big Data Engineer,"Pune, Maharashtra, India",2023-06-15 13:28:03
17,Data Science Team Lead,"Laurel, MD",2023-06-13 13:25:17
18,Data Analyst,"Warsaw, Poland",2023-10-16 13:36:54

In [54]:
df.loc[df['job_posted_date'] > '2023-05-01', ['job_title', 'job_location', 'job_posted_date']].head(15)

,job_title,job_location,job_posted_date
0,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",2023-06-16 13:44:15
2,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",2023-10-10 13:14:55
3,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",2023-07-04 13:01:41
4,Data Engineer- Sr Jobs,"Washington, DC",2023-08-07 14:29:36
5,GCP Data Engineer,Anywhere,2023-11-07 14:01:59
7,Data Engineer,Anywhere,2023-12-07 13:40:49
8,Technology & Operations Business Analyst,"Copenhagen, Denmark",2023-06-05 13:44:34
11,Data Engineer,"Colorado Springs, CO (+3 others)",2023-11-03 13:06:51
12,Stagiaire Data Analyst (H/F) - Lyon (69006),"Lyon, France",2023-12-22 13:24:41
13,Senior Data Engineer,"New York, NY",2023-11-15 13:08:52
14,Data Engineer,"Rio de Janeiro, State of Rio de Janeiro, Brazil",2023-07-13 13:17:51
15,Data Engineer,"Aberdeen, UK",2023-10-19 13:37:16
16,Big Data Engineer,"Pune, Maharashtra, India",2023-06-15 13:28:03
17,Data Science Team Lead,"Laurel, MD",2023-06-13 13:25:17
18,Data Analyst,"Warsaw, Poland",2023-10-16 13:36:54