## Pandas Index Management

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv("../Data/data_jobs.csv")
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'], errors='coerce')

* You can get or set properties of the index, such as its name or data type.  
* It's helpful for maintaining metadata or ensuring index compatibility in operations.
* `(index.name, index.dtype)`
    * `index.name` - name of the index
    * `index.dtype` - data type of the index

In [26]:
df.sample(3)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
605576,Data Analyst,Junior Data Analyst,Hong Kong,via Trabajo.org,Full-time,False,Hong Kong,2023-08-10 09:39:40,True,False,Hong Kong,NaN,NaN,NaN,Composers & Authors Society of Hong Kong Ltd,"['sql', 'python', 'excel', 'power bi']","{'analyst_tools': ['excel', 'power bi'], 'prog..."
187462,Data Engineer,Data Engineer Expérimenté H/F,Anywhere,via HelloWork,Full-time,True,France,2023-05-05 15:36:32,False,False,France,NaN,NaN,NaN,Onepoint,"['nosql', 'aws', 'redshift', 'spark', 'hadoop']","{'cloud': ['aws', 'redshift'], 'libraries': ['..."
82610,Data Engineer,"Principal Associate, Data Engineer","Fredericksburg, VA",via Monster,Full-time,False,"Texas, United States",2023-06-05 00:27:54,False,True,United States,NaN,NaN,NaN,Capital One,"['java', 'scala', 'python', 'nosql', 'sql', 'm...","{'cloud': ['redshift', 'snowflake', 'aws', 'az..."

In [4]:
# Index ispection
df.index

RangeIndex(start=0, stop=785741, step=1)

In [5]:
df.index.dtype

dtype('int64')

In [6]:
df.index.name

It has no name..

In [30]:
df.index.name = 'job_index'
df.index.name

'job_index'

In [9]:
df.sample(3)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
626620,Senior Data Scientist,Senior Open-Source Data Scientist Consultant,"Reston, VA",via Ladders,Full-time,False,Georgia,2023-08-11 12:40:10,False,True,United States,year,125000.0,NaN,Guidehouse,"['sql', 'python', 'r', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."
444219,Data Scientist,Head of Data Science,"Barcelona, Spain",via Jobijoba,Full-time,False,Spain,2023-09-01 16:39:39,False,False,Spain,NaN,NaN,NaN,M-KOPA,NaN,NaN
477969,Data Engineer,Sr. Bioinformatics Data & Application Engineer...,Switzerland,via Recruit.net,Full-time,False,Switzerland,2023-01-04 00:05:56,False,False,Switzerland,NaN,NaN,NaN,Nestlé SA,"['azure', 'linux']","{'cloud': ['azure'], 'os': ['linux']}"

## reset_index()

* `reset_index()`: Resets the DataFrame’s index to the default integer index. This is particularly useful after operations that alter the index, like sorting or filtering, to simplify further data manipulation.

In [31]:
df_usa = df[df['job_country'] == 'United States']

df_usa.head(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,NaN,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,NaN,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,NaN,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."

In [11]:
df_usa.index

Index([     0,      3,      5,      6,      9,     11,     13,     17,     26,
           27,
       ...
       785625, 785626, 785641, 785648, 785651, 785673, 785685, 785692, 785703,
       785705],
      dtype='int64', name='job_index', length=206292)

In [32]:
# Make "indexes" correlate with the actual indexes
df_usa.reset_index(inplace=True)
df_usa.head()

,job_index,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
2,5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,NaN,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
3,6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,NaN,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
4,9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,NaN,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."

Technically we could `.drop()` the `job_index`.

BUT, if we wanted to do some sort of merge operations in the future with our original DataFrame, this provides the unique `id` to do that.

In [23]:
median_pivot = df.pivot_table(values='salary_year_avg', index='job_title_short', aggfunc='median')
median_pivot

                           salary_year_avg
job_title_short
Business Analyst                   85000.0
Cloud Engineer                     90000.0
Data Analyst                       90000.0
Data Engineer                     125000.0
Data Scientist                    127500.0
Machine Learning Engineer         106415.0
Senior Data Analyst               111175.0
Senior Data Engineer              147500.0
Senior Data Scientist             155500.0
Software Engineer                  99150.0

In [24]:
median_pivot.reset_index(inplace=True)
median_pivot

             job_title_short  salary_year_avg
0           Business Analyst          85000.0
1             Cloud Engineer          90000.0
2               Data Analyst          90000.0
3              Data Engineer         125000.0
4             Data Scientist         127500.0
5  Machine Learning Engineer         106415.0
6        Senior Data Analyst         111175.0
7       Senior Data Engineer         147500.0
8      Senior Data Scientist         155500.0
9          Software Engineer          99150.0

## set_index()

* `set_index()`: Sets one or more existing columns as the index of the DataFrame. This is useful for timeseries data or when you want to index by specific attributes.

In [33]:
df_usa.set_index('job_index', inplace=True)

df_usa.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,NaN,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,NaN,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,NaN,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."

In [34]:
median_pivot.set_index('job_title_short', inplace=True)
median_pivot

                           salary_year_avg
job_title_short
Business Analyst                   85000.0
Cloud Engineer                     90000.0
Data Analyst                       90000.0
Data Engineer                     125000.0
Data Scientist                    127500.0
Machine Learning Engineer         106415.0
Senior Data Analyst               111175.0
Senior Data Engineer              147500.0
Senior Data Scientist             155500.0
Software Engineer                  99150.0

## sort_index()

* `sort_index()`: Sorts the DataFrame by the index (row labels), either ascending or descending. This helps in quickly organizing data by the index and is often used after `set_index()`.

In [37]:
median_pivot.sort_index(inplace=True)
median_pivot

                           salary_year_avg
job_title_short
Business Analyst                   85000.0
Cloud Engineer                     90000.0
Data Analyst                       90000.0
Data Engineer                     125000.0
Data Scientist                    127500.0
Machine Learning Engineer         106415.0
Senior Data Analyst               111175.0
Senior Data Engineer              147500.0
Senior Data Scientist             155500.0
Software Engineer                  99150.0

## Problems

In [38]:
pt = df.pivot_table(values='salary_year_avg', index='job_title_short', aggfunc=['median', 'min', 'max'])

pt

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  85000.0         16500.0        387460.0
Cloud Engineer                    90000.0         42000.0        280000.0
Data Analyst                      90000.0         25000.0        650000.0
Data Engineer                    125000.0         15000.0        525000.0
Data Scientist                   127500.0         27000.0        960000.0
Machine Learning Engineer        106415.0         30000.0        325000.0
Senior Data Analyst              111175.0         30000.0        425000.0
Senior Data Engineer             147500.0         35000.0        425000.0
Senior Data Scientist            155500.0         45000.0        890000.0
Software Engineer                 99150.0         28000.0        375000.0

In [39]:
pt.sort_values(by=('median', 'salary_year_avg'), ascending=False)

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Senior Data Scientist            155500.0         45000.0        890000.0
Senior Data Engineer             147500.0         35000.0        425000.0
Data Scientist                   127500.0         27000.0        960000.0
Data Engineer                    125000.0         15000.0        525000.0
Senior Data Analyst              111175.0         30000.0        425000.0
Machine Learning Engineer        106415.0         30000.0        325000.0
Software Engineer                 99150.0         28000.0        375000.0
Cloud Engineer                    90000.0         42000.0        280000.0
Data Analyst                      90000.0         25000.0        650000.0
Business Analyst                  85000.0         16500.0        387460.0

In [57]:
df_new = df.set_index('job_posted_date')
df_new.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_posted_date,,,,,,,,,,,,,,,,
2023-06-16 13:44:15,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
2023-01-14 13:18:07,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2023-10-10 13:14:55,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
2023-07-04 13:01:41,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
2023-08-07 14:29:36,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [54]:
df_new.reset_index(drop=True, inplace=True)

df_new.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [49]:
pt_new = df.pivot_table(values='salary_year_avg', index='company_name', aggfunc='median')
pt_new.sort_index(inplace=True, ascending=False)
pt_new.head()

                                    salary_year_avg
company_name
​Illinois State Board of Education          62536.0
Технологическая компания                   280000.0
ЛАНИТ                                      400000.0
ztp                                         95000.0
zooplus SE                                 161750.0

In [51]:
pt_new = df.pivot_table(values='salary_year_avg', index='job_title_short', aggfunc='median')
pt_new.reset_index(inplace=True)
pt_new.set_index('salary_year_avg', inplace=True)
pt_new.head()

                  job_title_short
salary_year_avg
85000.0          Business Analyst
90000.0            Cloud Engineer
90000.0              Data Analyst
125000.0            Data Engineer
127500.0           Data Scientist